### ISSUE TITLE
Method tracked as introduced when moved to a different file

### ISSUE THREAD

**Issue by flozender** [jodavimehran/code-tracker#12]
`Pattern createPattern(String pattern)` in line `R176` was moved to `src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtils.java` from `src/main/java/com/puppycrawl/tools/checkstyle/utils/Utils.java` in [this commit](https://github.com/checkstyle/checkstyle/commit/cdf3e56bacd3895262af8a1df9ca5c81f4071970), but Code Tracker detects it as `introduced: added with new class`.

Please let me know if you need any additional information regarding this bug.

**Comment by tsantalis** [comment]
@jodavimehran 
When running with all files in the commit we get the following refactorings:
**Rename Class** `com.puppycrawl.tools.checkstyle.utils.Utils` renamed to `com.puppycrawl.tools.checkstyle.utils.TokenUtils`
**Rename Class** `com.puppycrawl.tools.checkstyle.utils.UtilsTest` renamed to `com.puppycrawl.tools.checkstyle.utils.CommonUtilsTest`

**Extract Class** `com.puppycrawl.tools.checkstyle.utils.CommonUtils` from class `com.puppycrawl.tools.checkstyle.utils.Utils`
**Extract Class** `com.puppycrawl.tools.checkstyle.utils.TokenUtilsTest` from class `com.puppycrawl.tools.checkstyle.utils.UtilsTest`

Based on the commit message
> Utils class has been splitted to CommonUtils and TokenUtils

This seems like a **Split Class** scenario.

**Comment by tsantalis** [comment]
The history of the method after the fix


Commit ID: 0fd69594a4c3e82f92f93f0371791da66938f8c3
Date: 2001-06-22T13:24:24
Before: src/checkstyle/com.puppycrawl.tools.checkstyle.VerifierImpl#createRE(String)
After: src/checkstyle/com.puppycrawl.tools.checkstyle.VerifierImpl#createRE(String)
introduced: added with new class

Commit ID: f0f7f3e762ffef78dcf82bf1611c10da48b96cb9
Date: 2001-06-28T13:10:22
Before: src/checkstyle/com.puppycrawl.tools.checkstyle.VerifierImpl#createRE(String)
After: src/checkstyle/com.puppycrawl.tools.checkstyle.VerifierImpl#createRE(String)
body change: Body Change

Commit ID: 8d6fa332a9c8b0c350dfcb1d923d70bc5f3d921b
Date: 2002-01-14T02:56:15
Before: src/checkstyle/com.puppycrawl.tools.checkstyle.VerifierImpl#createRE(String)
After: src/checkstyle/com.puppycrawl.tools.checkstyle.Verifier#createRE(String)
moved: Pull Up Method	private createRE(aPattern String) : RE from class com.puppycrawl.tools.checkstyle.VerifierImpl to private createRE(aPattern String) : RE from class com.puppycrawl.tools.checkstyle.Verifier

Commit ID: 7b849d58d5a6da2a1384091e3fc7ebb07ba1d957
Date: 2002-05-14T04:41:16
Before: src/checkstyle/com.puppycrawl.tools.checkstyle.Verifier#createRE(String)
After: src/checkstyle/com.puppycrawl.tools.checkstyle.Verifier#createRE(String)
body change: Body Change

Commit ID: 59222296258fecc02db44eeae1cb65b44b68c267
Date: 2002-10-24T14:33:31
Before: src/checkstyle/com.puppycrawl.tools.checkstyle.Verifier#createRE(String)
After: src/checkstyle/com.puppycrawl.tools.checkstyle.api.Utils#createRE(String)
modifier change: Change Method Access Modifier	private to public in method public createRE(aPattern String) : RE from class com.puppycrawl.tools.checkstyle.api.Utils
moved: Move Method	private createRE(aPattern String) : RE from class com.puppycrawl.tools.checkstyle.Verifier to public createRE(aPattern String) : RE from class com.puppycrawl.tools.checkstyle.api.Utils
body change: Body Change

Commit ID: 419d9243861ac99e80a7783547a51adf8b284817
Date: 2002-12-06T11:23:46
Before: src/checkstyle/com.puppycrawl.tools.checkstyle.api.Utils#createRE(String)
After: src/checkstyle/com.puppycrawl.tools.checkstyle.api.Utils#createRE(String)
exception change: Add Thrown Exception Type	ConversionException in method public createRE(aPattern String) : RE from class com.puppycrawl.tools.checkstyle.api.Utils

Commit ID: b0db9beefa6e08f88e72dc2868767f7a9db62f51
Date: 2002-12-08T11:58:34
Before: src/checkstyle/com.puppycrawl.tools.checkstyle.api.Utils#createRE(String)
After: src/checkstyle/com.puppycrawl.tools.checkstyle.api.Utils#createRE(String)
body change: Body Change

Commit ID: e27489c7721909245ea5055eac3b9c7c659081f6
Date: 2005-05-11T16:48:11
Before: src/checkstyle/com.puppycrawl.tools.checkstyle.api.Utils#createRE(String)
After: src/checkstyle/com.puppycrawl.tools.checkstyle.api.Utils#createPattern(String)
return type change: Change Return Type	RE to Pattern in method public createPattern(aPattern String) : Pattern from class com.puppycrawl.tools.checkstyle.api.Utils
rename: Rename Method	public createRE(aPattern String) : RE renamed to public createPattern(aPattern String) : Pattern in class com.puppycrawl.tools.checkstyle.api.Utils
body change: Body Change

Commit ID: 35d1673788bbbac8263fdb69275dc6a63b095a24
Date: 2006-07-07T03:44:16
Before: src/checkstyle/com.puppycrawl.tools.checkstyle.api.Utils#createPattern(String)
After: src/checkstyle/com.puppycrawl.tools.checkstyle.api.Utils#createPattern(String)
body change: Body Change

Commit ID: f1efb27670a93690577f1bae17fc9dcbd88a795d
Date: 2014-03-04T17:18:11
Before: src/checkstyle/com.puppycrawl.tools.checkstyle.api.Utils#createPattern(String)
After: src/main/java/com.puppycrawl.tools.checkstyle.api.Utils#createPattern(String)
container change: Move Source Folder	src/checkstyle to src/main/java

Commit ID: b94bac0719851b65b59b4aafc5bd3ef029321ed7
Date: 2015-01-19T14:19:41
Before: src/main/java/com.puppycrawl.tools.checkstyle.api.Utils#createPattern(String)
After: src/main/java/com.puppycrawl.tools.checkstyle.api.Utils#createPattern(String)
parameter change: Rename Parameter	aPattern : String to pattern : String in method public createPattern(pattern String) : Pattern from class com.puppycrawl.tools.checkstyle.api.Utils
body change: Body Change

Commit ID: 1c15b6a36baa68dc3f2ebdf9baac131e98bb9e04
Date: 2015-03-15T21:22:16
Before: src/main/java/com.puppycrawl.tools.checkstyle.api.Utils#createPattern(String)
After: src/main/java/com.puppycrawl.tools.checkstyle.Utils#createPattern(String)
moved: Move Method	public createPattern(pattern String) : Pattern from class com.puppycrawl.tools.checkstyle.api.Utils to public createPattern(pattern String) : Pattern from class com.puppycrawl.tools.checkstyle.Utils

Commit ID: ebd4afdebe8ee09c0e6c7d1239e2ca982f87e51c
Date: 2015-03-27T21:39:02
Before: src/main/java/com.puppycrawl.tools.checkstyle.Utils#createPattern(String)
After: src/main/java/com.puppycrawl.tools.checkstyle.Utils#createPattern(String)
body change: Body Change

Commit ID: 97f0829897b9000236489295f89d57a77d8006b4
Date: 2015-03-27T22:34:34
Before: src/main/java/com.puppycrawl.tools.checkstyle.Utils#createPattern(String)
After: src/main/java/com.puppycrawl.tools.checkstyle.Utils#createPattern(String)
body change: Body Change

Commit ID: 081c654df8d801f576506265681654a730cfc375
Date: 2015-08-01T20:24:47
Before: src/main/java/com.puppycrawl.tools.checkstyle.Utils#createPattern(String)
After: src/main/java/com.puppycrawl.tools.checkstyle.Utils#createPattern(String)
exception change: Remove Thrown Exception Type	ConversionException in method public createPattern(pattern String) : Pattern from class com.puppycrawl.tools.checkstyle.Utils

Commit ID: ed595de84fba2db507adaf01d04cb089a5e0bac5
Date: 2015-08-27T12:17:01
Before: src/main/java/com.puppycrawl.tools.checkstyle.Utils#createPattern(String)
After: src/main/java/com.puppycrawl.tools.checkstyle.utils.Utils#createPattern(String)
container change: Move Class	com.puppycrawl.tools.checkstyle.Utils moved to com.puppycrawl.tools.checkstyle.utils.Utils

Commit ID: cdf3e56bacd3895262af8a1df9ca5c81f4071970
Date: 2015-08-27T12:17:01
Before: src/main/java/com.puppycrawl.tools.checkstyle.utils.Utils#createPattern(String)
After: src/main/java/com.puppycrawl.tools.checkstyle.utils.CommonUtils#createPattern(String)
container change: Rename Class	com.puppycrawl.tools.checkstyle.utils.Utils renamed to com.puppycrawl.tools.checkstyle.utils.CommonUtils

Commit ID: f2c6263e151e8a7300755b36fbb41511c0a0cca1
Date: 2015-10-30T04:12:23
Before: src/main/java/com.puppycrawl.tools.checkstyle.utils.CommonUtils#createPattern(String)
After: src/main/java/com.puppycrawl.tools.checkstyle.utils.CommonUtils#createPattern(String)
body change: Body Change
