### ISSUE TITLE
Incorrect block history - `try` block - checkstyle

### ISSUE THREAD

**Issue by flozender** [jodavimehran/code-tracker#133]
https://github.com/checkstyle/checkstyle/commit/08d6efe49d2960d9bd61bfb9cca65910f0c19b58#diff-b48cc2ff38026f94180847550cd260a0ebefb4a9cb9635e39f5fa2046311d72bR157

CodeTracker indicates this block to have been `introduced`, however, it was moved from the parent method [`configure`](https://github.com/checkstyle/checkstyle/commit/08d6efe49d2960d9bd61bfb9cca65910f0c19b58#diff-b48cc2ff38026f94180847550cd260a0ebefb4a9cb9635e39f5fa2046311d72bL133) and a body change was performed.

**Comment by tsantalis** [comment]
This is a case of a Split Method
`public void configure(Configuration aConfig)`
is split to two methods
`public void finishLocalSetup()`
`protected void setupChild(Configuration aChildConf)`

There are no call sites to help us find the split.

**Comment by flozender** [comment]
Fixed with latest commit.
