### ISSUE TITLE
Incorrect block history - `synchronized` statement - lucene-solr

### ISSUE THREAD

**Issue by flozender** [jodavimehran/code-tracker#134]
https://github.com/apache/lucene-solr/commit/acb3c379427193036f3d56503529400736ac5dff#diff-edbb11369e2e565210ea9761ee167ac0c6a39521c0e71f8af24f25f4092c740aR711

CodeTracker detects this block as being introduced, however, it is present in the parent commit. 

The oracle file has been corrected.

**Comment by flozender** [comment]
[Oracle file](https://github.com/flozender/CodeTracker-API/blob/881163e74c96afd3a131ed158854c456753faa88/src/main/resources/oracle/block/test/invalid/lucene-solr-IndexWriter-writeSomeDocValuesUpdates-SYNCHRONIZED_STATEMENT.json)

**Comment by tsantalis** [comment]
There are no mapped statements within the body of the `synchronized` statement
The statement
`rld.writeFieldUpdates(directory, bufferedUpdatesStream.getCompletedDelGen(), infoStream);`
becomes
`if (rld.writeFieldUpdates(directory, globalFieldNumberMap, bufferedUpdatesStream.getCompletedDelGen(), infoStream))`

![Screenshot from 2023-10-07 19-09-00](https://github.com/jodavimehran/code-tracker/assets/1483516/a5d49038-340d-4ed9-91b9-b668084f07c9)
