### ISSUE TITLE
Incorrect mapping - checkstyle if block (4cbd709)

### ISSUE THREAD

**Issue by flozender** [jodavimehran/code-tracker#161]
https://github.com/checkstyle/checkstyle/commit/4cbd709c019cf1b69796858506d673f7b66d37c7#diff-b48cc2ff38026f94180847550cd260a0ebefb4a9cb9635e39f5fa2046311d72bR234

Tracking block `if(R234)` in project Checkstyle and commit [`4cbd709`](https://github.com/checkstyle/checkstyle/commit/4cbd709c019cf1b69796858506d673f7b66d37c7), `R234` is mapped to ~L479~ `L356`, but it should be mapped to `L424`.

**Comment by tsantalis** [comment]
@flozender 

From what I see in the diff (screenshot below) R234 is mapped to L424

L479 is the closing curly bracket of a catch block. There is no way it can be matched with that.

![Screenshot from 2023-08-29 07-49-37](https://github.com/jodavimehran/code-tracker/assets/1483516/49e4ac72-27ce-473b-9027-dd138bcb2119)

**Comment by flozender** [comment]
@tsantalis 
Sorry, that is a mistake. It maps with `L356`. The left block goes on to being mapped with a block on the line `L479` in another commit and I mixed up the numbers.


![image](https://github.com/jodavimehran/code-tracker/assets/40818234/e17f1da4-6291-4648-8d73-1e9c67fac99d)

**Comment by tsantalis** [comment]
After my fix the history starting from https://github.com/checkstyle/checkstyle/commit/4cbd709c019cf1b69796858506d673f7b66d37c7 is as follows

Commit ID: b84b3fd04ad9c45e1466e35b707a2b59f5baf66b
Date: 2002-09-24T06:34:11
Before: src/checkstyle/com.puppycrawl.tools.checkstyle.Checker#processNEW(String)$if(479-484)
After: src/checkstyle/com.puppycrawl.tools.checkstyle.Checker#processNEW(String)$if(479-484)
introduced: added with method
