### ISSUE TITLE
Invalid Change History - src/java/org.apache.commons.lang.time.DurationFormatUtils#formatPeriod(long, long, String, boolean, TimeZone)$while(319-323)

### ISSUE THREAD

**Issue by flozender** [jodavimehran/code-tracker#27]
In commit [`4f514d5eb3e80703012df9be190ae42d35d25bdc`](https://github.com/apache/commons-lang/commit/4f514d5eb3e80703012df9be190ae42d35d25bdc?diff=split#diff-ad3693552a9088880c9418f7db7847718c91c98f33ac15bfbcaf14c971333b19R319) and file `src/java/org/apache/commons/lang/time/DurationFormatUtils.java`, element `src/java/org.apache.commons.lang.time.DurationFormatUtils#formatPeriod(long, long, String, boolean, TimeZone)$while(319-323)` was identified as being `expression change`, which may not be accurate. 

Oracle filename: `commons-lang-DurationFormatUtils-formatPeriod-WHILE_STATEMENT.json`

**Comment by flozender** [comment]
Goes on to match the `if` block here but doesn't match back to the `while`. Commit [5fb6521ab990c0c9ec655ca71d8c77060aedb0e5](https://github.com/apache/commons-lang/commit/5fb6521ab990c0c9ec655ca71d8c77060aedb0e5#diff-ad3693552a9088880c9418f7db7847718c91c98f33ac15bfbcaf14c971333b19R315).

**Comment by flozender** [comment]
As discussed, this could be modeled under a new type of change: `composite type changed`

**Comment by tsantalis** [comment]
`if` becomes `while`
```java
if (days < 0) {
    days += start.getActualMaximum(Calendar.DAY_OF_MONTH);
    // Multiple answers possible. 
    // For example, for Jan 15th to March 10th. If I count days-first it is 
    // 1 month and 26 days, but if I count month-first then it is 1 month and 23 days.
    // Here we choose the former. 
    months -= 1;
    start.add(Calendar.MONTH, 1);
}
```
becomes
```java
while (days < 0) {
    days += start.getActualMaximum(Calendar.DAY_OF_MONTH);
    months -= 1;
    start.add(Calendar.MONTH, 1);
}
```

**Comment by tsantalis** [comment]
in https://github.com/apache/commons-lang/commit/5fb6521ab990c0c9ec655ca71d8c77060aedb0e5
```java
while (days < 0) {
    end.add(Calendar.MONTH, -1);
    days += end.getActualMaximum(Calendar.DAY_OF_MONTH);
    // HEN: It's a tricky subject. Jan 15th to March 10th. If I count days-first it is 
    // 1 month and 26 days, but if I count month-first then it is 1 month and 23 days.
    // Also it's contextual - if asked for no M in the format then I should probably 
    // be doing no calculating here.
    months -= 1;
    end.add(Calendar.MONTH, 1);
}
```
becomes
```java
if (days < 0) {
    days += start.getActualMaximum(Calendar.DAY_OF_MONTH);
    // It's a tricky subject. Jan 15th to March 10th. If I count days-first it is 
    // 1 month and 26 days, but if I count month-first then it is 1 month and 23 days.
    // Here we choose the former. 
    // Also it's contextual - if asked for no M in the format then I should probably 
    // be doing no calculating here.
    months -= 1;
}
```
