### ISSUE TITLE
Block History is Empty

### ISSUE THREAD

**Issue by flozender** [jodavimehran/code-tracker#29]
When tracking these blocks, the history is completely empty, which shouldn't be the case. 

1. https://github.com/junit-team/junit5/blob/77cfe71e7f787c59626198e25350545f41e968bd/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassTestDescriptor.java#L374-L376

2. https://github.com/spring-projects/spring-framework/blob/b325c74216fd9564a36602158fa1269e2e832874/spring-context/src/main/java/org/springframework/context/annotation/ConfigurationClassBeanDefinitionReader.java#L231-L233

3. https://github.com/square/okhttp/blob/5224f3045ba9b171fce521777edf389f9206173c/okhttp-urlconnection/src/main/java/okhttp3/internal/huc/OkHttpURLConnection.java#L471-L475

**Comment by tsantalis** [comment]
**Case 2**
======================================================
Commit ID: 14bd47551900ced88eeacf2a5f63c187ff72028c
Date: 2009-04-19T23:45:31
Before: org.springframework.context/src/main/java/org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader#loadBeanDefinitionsForModelMethod(ConfigurationClassMethod)$if(156-158)
After: org.springframework.context/src/main/java/org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader#loadBeanDefinitionsForModelMethod(ConfigurationClassMethod)$if(156-158)
introduced: new block
======================================================

**Comment by tsantalis** [comment]
**Case 3**

There is a merge commit happening in https://github.com/square/okhttp/commit/00c9db7859ed4edac380b25c3be61afd9ece0e5d
and the rightMethod cannot be located in `c9a89876de476983f273edbf108c365127c18c5e`.

> okhttp-urlconnection/src/main/java/okhttp3.internal.huc.HttpURLConnectionImpl#(private)getResponse():Response[IOException]{-1659955927}{f140b118eca92e56373cc4e8549aee4c084fc77e0237d206f1cd8759ab64076661c4ea214d5b265f36684a23a88da30ab5b5a04114fd0baa6d5b314577a1b4e0}<c9a89876de476983f273edbf108c365127c18c5e>

> okhttp-urlconnection/src/main/java/okhttp3.internal.huc.HttpURLConnectionImpl#(private)getResponse():HttpEngine[IOException]{2096466661}{1c2e7cf7319c266c07e0fd6bb9d4b17dd15498841f26ca5adf71c2c2346f01feeb5569157990c8790b3dccaeb348e701e49587e8d040babe0c947772e14d7da9}<c9a89876de476983f273edbf108c365127c18c5e>

**Comment by flozender** [comment]
Processed commits from codetracker
```
processing a2fb46b1a459aa1d014a732c21575acb7ac3d4ef
processing 351b3d6bf786e001f80ab3a7a933d4279cafbf83
processing aac684aeae32ff18e443799a3ccff6de9d68a684
processing 2db8c41b3b0f0476c0e8735f4d57562d50f32ffa
processing 83b9dd427535bce39be43a9e8224cdbc352d7427
processing 2b8ad31b084af93ad202a1b835e5be63ac58a269
processing 591d59556153555c9f5b56bf601780a817defc09
processing 764c35e7842c8828e6686e318facfca0a11d49ba
processing a4d3082d2f705598c753702863a3068bc36621cc
processing c5187583bbfe93fe58db80f95b5b478c84180c29
processing e3b3180f9c4cc8821e9092955127935fa956a988
processing 2843933b4b4778451d1d43822db1a148bf2aa7ea
processing ec39c462324c0a54e6abf06cbf8079298056b7d5
processing 084b06b48bae2b566bb1be3415b6c847d8ea3682 (Block introduced in this commit)
processing 4f24a30c12032b7033884a630696014afd3e77cb
processing 51e4e39842596ece3d0d2c327911a7702607cb3e
processing 2dade17682071a3e1d60df4113795117e5c1833c
processing 2b1f9a20bac5d99acf5a8be36754e5a1dadaf448
processing d3675a5e0f7ca0287d3441d1dc1284ea7b06a26d
processing 38d570a6b28664b398cfa50c5c243c3631cde997
processing f2461183e8a70bae2362a5237772844a48e16100
processing c9334bd90f1ba826ea75198a3b3507c5ba99fd4e
processing 98ae0fb92c9335ec17f8710376183e18f5edd355
processing 02d6b4e78c4f1bda5f20e3089af024c58fe6baf6
processing 3b44fa37675c1d68298283ae4b8b45cd5771888d
processing c9a89876de476983f273edbf108c365127c18c5e
```

Looking into:

[`084b06b48bae2b566bb1be3415b6c847d8ea3682`](https://github.com/square/okhttp/commit/084b06b48bae2b566bb1be3415b6c847d8ea3682#diff-1b28d42593f77d6f93b69b67965708a9312b4da61d8ddacad3e8e4018135bfb3R425) Jun 21, 2016 (Try block was introduced)

[`3b44fa37675c1d68298283ae4b8b45cd5771888d`](https://github.com/square/okhttp/commit/3b44fa37675c1d68298283ae4b8b45cd5771888d) Dec 21, 2015 (Changes made to the file but not the method)

[`00c9db7859ed4edac380b25c3be61afd9ece0e5d`](https://github.com/square/okhttp/commit/00c9db7859ed4edac380b25c3be61afd9ece0e5d) Dec 19, 2015 (Merge commit referenced above, no changes made to file)

[`c9a89876de476983f273edbf108c365127c18c5e`](https://github.com/square/okhttp/commit/c9a89876de476983f273edbf108c365127c18c5e) Dec 16, 2015 (Complete rename of com.squareup.okhttp to okhttp3)


Last seen commit by codetracker [`c9a89876de476983f273edbf108c365127c18c5e`](https://github.com/square/okhttp/commit/c9a89876de476983f273edbf108c365127c18c5e)

Commits after this commit, which can be ignored (No changes made to the file):

    54dc2df914f2aae37fb48cc2c2f7560ee664bc2b
    f9776c4adfec3e649a8aa284276d9ddb50cf17a9
    52fa3cf24d0f0c28e811c966b3a78880c06ca19d
    f5d0abd0590d95a05da6e15479f2b27c3daf761e
    513fec7b7f9d308c943e7765011f7a4c25df51fa
    91abd6c4388067e762f64845314a521e43a1702e
    d5c93840c96fc13390d9e77d7e2901ece7ce5d9e
    b63841d3a3922440c258098190371f1e17d977c1
    992dd934f061a21f8a802ed8fd8d99b75047dba8
    efc9df1ca7698dda695b4065729ab033c3d65d2a
    5f22afe9e55ad5ca47513e66e587178155a219ff

Next relevant commit:

[`71ae4df298f42039579fd6e3c6d9d9060ac91214`](https://github.com/square/okhttp/blob/71ae4df298f42039579fd6e3c6d9d9060ac91214/okhttp-urlconnection/src/main/java/com/squareup/okhttp/internal/huc/HttpURLConnectionImpl.java#L386) Dec 15, 2015 (Changes made to the file but not the method)

Codetracker should continue tracking from this commit. 

The method here is [`private HttpEngine getResponse()`](https://github.com/square/okhttp/blob/71ae4df298f42039579fd6e3c6d9d9060ac91214/okhttp-urlconnection/src/main/java/com/squareup/okhttp/internal/huc/HttpURLConnectionImpl.java#L386)

See all relevant commits [here](https://github.com/square/okhttp/commits/5224f3045ba9b171fce521777edf389f9206173c?after=5224f3045ba9b171fce521777edf389f9206173c+1014&branch=5224f3045ba9b171fce521777edf389f9206173c&qualified_name=5224f3045ba9b171fce521777edf389f9206173c).

**Comment by tsantalis** [comment]
Case 3 fixed
======================================================
Commit ID: 084b06b48bae2b566bb1be3415b6c847d8ea3682
Date: 2016-06-21T18:30
Before: okhttp-urlconnection/src/main/java/okhttp3.internal.huc.HttpURLConnectionImpl#getResponse()$try(425-429)
After: okhttp-urlconnection/src/main/java/okhttp3.internal.huc.HttpURLConnectionImpl#getResponse()$try(425-429)
introduced: new block
======================================================
