### ISSUE TITLE
Invalid Change History - junit-jupiter-engine/src/main/java/org.junit.jupiter.engine.descriptor.ClassTestDescriptor#invokeBeforeAllMethods(ExtensionRegistry, ContainerExtensionContext, ThrowableCollector)$for(217-222)

### ISSUE THREAD

**Issue by flozender** [jodavimehran/code-tracker#62]
In commit [`62c433c14ce9d70fa5b82ef385a6e15c22cc0003`](https://github.com/junit-team/junit5/commit/62c433c14ce9d70fa5b82ef385a6e15c22cc0003?diff=split#diff-3679a3039f048d756df1feebd214cc17df7b0a686dc3be77f24bff5bc61bbf4cR217) and file `junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassTestDescriptor.java`, element `junit-jupiter-engine/src/main/java/org.junit.jupiter.engine.descriptor.ClassTestDescriptor#invokeBeforeAllMethods(ExtensionRegistry, ContainerExtensionContext, ThrowableCollector)$for(217-222)` was identified as being `introduced`, which may not be accurate. 

Oracle filename: `junit5-ClassTestDescriptor-invokeBeforeAllMethods-ENHANCED_FOR_STATEMENT.json`

**Comment by tsantalis** [comment]
@flozender 
To continue tracking this code from the Streams API equivalent statement
```java
this.beforeAllMethods.forEach(
			method -> executeAndMaskThrowable(() -> executableInvoker.invoke(method, context, registry)));
```
we need to change the abstraction level of `Block`.`composite` from `CompositeStatementObject` to `AbstractStatement`
