### ISSUE TITLE
Invalid Change History - spring-context/src/main/java/org.springframework.context.annotation.ConfigurationClassParser#doProcessConfigurationClass(ConfigurationClass, SourceClass)$if(248-254)

### ISSUE THREAD

**Issue by flozender** [jodavimehran/code-tracker#69]
In commit [`9dfbc5326b17ab48a0335efa4d82e15e6df0dfae`](https://github.com/spring-projects/spring-framework/commit/9dfbc5326b17ab48a0335efa4d82e15e6df0dfae?diff=split#diff-16816d3d3dfc16634ac0b8df8950db179ed793fce345c8bf7ef2dfaa2db95ae6R248) and file `spring-context/src/main/java/org/springframework/context/annotation/ConfigurationClassParser.java`, element `spring-context/src/main/java/org.springframework.context.annotation.ConfigurationClassParser#doProcessConfigurationClass(ConfigurationClass, SourceClass)$if(248-254)` was identified as being `introduced`, which may not be accurate. 

Oracle filename: `spring-framework-ConfigurationClassParser-doProcessConfigurationClass-IF_STATEMENT.json`

**Comment by flozender** [comment]
This is a case of `Invert Condition Refactoring`

**Comment by tsantalis** [comment]
![Screenshot from 2022-12-05 13-49-16](https://user-images.githubusercontent.com/1483516/205718411-ba08bcf7-0095-4034-a41b-c9f21fe748a4.png)
