### ISSUE TITLE
Invalid Change History - org.springframework.beans/src/main/java/org.springframework.beans.factory.support.ConstructorResolver#instantiateUsingFactoryMethod(String, RootBeanDefinition, Object[])$if(459-465)

### ISSUE THREAD

**Issue by flozender** [jodavimehran/code-tracker#71]
In commit [`17dfc8b0fcf3e2a02ab0db48af1d309981bbe6c2`](https://github.com/spring-projects/spring-framework/commit/17dfc8b0fcf3e2a02ab0db48af1d309981bbe6c2#diff-ebd0ea1d06e527f37e953e4f287020385274073bf8f50074e741e0601f3776f1R459?diff=split#diff-ebd0ea1d06e527f37e953e4f287020385274073bf8f50074e741e0601f3776f1R459) and file `org.springframework.beans/src/main/java/org/springframework/beans/factory/support/ConstructorResolver.java`, element `org.springframework.beans/src/main/java/org.springframework.beans.factory.support.ConstructorResolver#instantiateUsingFactoryMethod(String, RootBeanDefinition, Object[])$if(459-465)` was identified as being `introduced`, which may not be accurate. 

Oracle filename: `spring-framework-ConstructorResolver-instantiateUsingFactoryMethod-IF_STATEMENT-17.json`

**Comment by tsantalis** [comment]
@flozender 
The `else-if` **L448-453** has been moved to **R481-486**
Thus, R459-465 is a newly introduced `else-if`

The AST diff is very clear:

![Screenshot from 2022-12-05 16-43-31](https://user-images.githubusercontent.com/1483516/205749082-ecd67b30-b2d2-4d5d-a99d-4d69de7eff3c.png)

**Comment by flozender** [comment]
Yes, I agree. The parent `if` being similar made me feel like the `else-if` just underwent a body change, which is not the case.
