### ISSUE TITLE
Invalid Change History - org.springframework.core/src/main/java/org.springframework.core.convert.support.GenericConversionService#getConverter(TypeDescriptor, TypeDescriptor)$if(247-274)

### ISSUE THREAD

**Issue by flozender** [jodavimehran/code-tracker#73]
In commit [`bf03d0d56f9fcfc4757bd3ab35e40c3f528fe710`](https://github.com/spring-projects/spring-framework/commit/bf03d0d56f9fcfc4757bd3ab35e40c3f528fe710?diff=split#diff-1137048ce8b11fb607a9505e227eb98dca0924b39b4a0b626527471a2c3a2451R247) and file `org.springframework.core/src/main/java/org/springframework/core/convert/support/GenericConversionService.java`, element `org.springframework.core/src/main/java/org.springframework.core.convert.support.GenericConversionService#getConverter(TypeDescriptor, TypeDescriptor)$if(247-274)` was identified as being `introduced`, which may not be accurate. 

Oracle filename: `spring-framework-GenericConversionService-getConverter-IF_STATEMENT.json`

**Comment by tsantalis** [comment]
@flozender 
R247-274 is a newly introduced `if` that handles the new `converterCache` functionality.
It's clear that the old code L230-237 has been moved (with the same statement order) inside the `else` block of the newly introduced `if` R247-274

The diff shows everything clearly:

![Screenshot from 2022-12-06 20-59-48](https://user-images.githubusercontent.com/1483516/206069537-a8ab8035-f13f-4bfe-a34c-5b2739b65508.png)
