### ISSUE TITLE
Broken oracle history after recent build

### ISSUE THREAD

**Issue by flozender** [jodavimehran/code-tracker#77]
These oracle files lost some commits from their histories after the recent build.

- [x] [`src/main/resources/oracle/block/training/false/jgit-PackWriter-findObjectsToPack-IF_STATEMENT-22.json`](https://github.com/flozender/CodeTracker-API/commit/cfedbf4b775f58004dd25eab0689d8b9c2e73f32#diff-47ddefc71383071aaad73671a2282965e47faa709875ea8fb89d38f9395c9ed7) (This [commit](https://github.com/flozender/jgit/blob/733780e8a158b7bc45b8b687ac353ecadc905a63/org.eclipse.jgit/src/org/eclipse/jgit/storage/pack/PackWriter.java#L1241) is missing)

**Solved**

- [x] [`src/main/resources/oracle/block/training/invalid/reported/hibernate-orm-DefaultRefreshEventListener-onRefresh-IF_STATEMENT-4.json`](https://github.com/flozender/CodeTracker-API/commit/cfedbf4b775f58004dd25eab0689d8b9c2e73f32#diff-5d5f9ea5a3d087dccba3d467003cda08ac15bd7e13719692b8117406a23e5674)
- [x] [`src/main/resources/oracle/block/training/true/flink-LocatableInputSplitAssigner-getNextInputSplit-IF_STATEMENT-13.json`](https://github.com/flozender/CodeTracker-API/commit/cfedbf4b775f58004dd25eab0689d8b9c2e73f32#diff-42246a96a8a0ec01199b3b6bd440c2a9536492bc15c68ffea84147712e8fbffc) (Interesting case where the exact same block is present throughout the method but only the correct one is mapped)
- [x] [`src/main/resources/oracle/block/training/false/hibernate-orm-DefaultRefreshEventListener-onRefresh-IF_STATEMENT-6.json`](https://github.com/flozender/CodeTracker-API/commit/cfedbf4b775f58004dd25eab0689d8b9c2e73f32#diff-0ee5a7864435b8bc20f69fa064d25a4fd64e9b46d3089d77c1377c5f9026fd87)
- [x] [`src/main/resources/oracle/block/training/false/commons-lang-DurationFormatUtils-formatPeriod-WHILE_STATEMENT-4.json`](https://github.com/flozender/CodeTracker-API/commit/cfedbf4b775f58004dd25eab0689d8b9c2e73f32#diff-5f3a62f94119ef3212d43c9506d99036b1a7fea0a4d1eea9e27abf0c135bb4b0)
- [x] [`src/main/resources/oracle/block/training/false/spring-framework-AbstractMessageConverterMethodProcessor-writeWithMessageConverters-ENHANCED_FOR_STATEMENT-3.json`](https://github.com/flozender/CodeTracker-API/commit/cfedbf4b775f58004dd25eab0689d8b9c2e73f32#diff-fd0577991a6c38f0910cee1ebfc3e067fd2ddc5bc27db7b69724439986aaa3b1)
- [x] [`src/main/resources/oracle/block/training/true/commons-lang-FastDatePrinter-parsePattern-IF_STATEMENT-5.json`](https://github.com/flozender/CodeTracker-API/commit/cfedbf4b775f58004dd25eab0689d8b9c2e73f32#diff-e459b6595b5bb561149bd811cefbf47b50d59437bb59bd0e1905b26fc702e630)
- [x] [`src/main/resources/oracle/block/training/true/flink-PojoSerializer-deserialize-TRY_STATEMENT.json`](https://github.com/flozender/CodeTracker-API/commit/cfedbf4b775f58004dd25eab0689d8b9c2e73f32#diff-7f32c8451089c54d9d65075cdb7caca07e1d3e3084c6090fd8dbb06ed4b8bb43)

**Comment by tsantalis** [comment]
`src/main/resources/oracle/block/training/false/jgit-PackWriter-findObjectsToPack-IF_STATEMENT-22.json` is correct.
Clearly, the previous json was incorrect and the current one is correct.
https://github.com/flozender/jgit/commit/733780e8a158b7bc45b8b687ac353ecadc905a63#diff-abd82c6e2dd33f06197069caefc17d62b5bdcaa11e7a981cdb13c814df1f9926R1240-R1242
I am closing the issue.
