### ISSUE TITLE
Invalid Change History - org.eclipse.jgit/src/org.eclipse.jgit.lib.IndexDiff#diff(ProgressMonitor, int, int, String)$if(325-336)

### ISSUE THREAD

**Issue by flozender** [jodavimehran/code-tracker#84]
In commit [`298486a7c320629de12f9506e0133686a7382b01`](https://github.com/flozender/jgit/commit/298486a7c320629de12f9506e0133686a7382b01?diff=split#diff-412275d04b0bd690cda01a7775aa1eb076e7d1cd385d80bdb831f885891d9c5dR325) and file `org.eclipse.jgit/src/org/eclipse/jgit/lib/IndexDiff.java`, element `org.eclipse.jgit/src/org.eclipse.jgit.lib.IndexDiff#diff(ProgressMonitor, int, int, String)$if(325-336)` was identified as being `introduced`, which may not be accurate. 

Oracle filename: `jgit-IndexDiff-diff-IF_STATEMENT-20.json`

**Comment by flozender** [comment]
There is a block with the same expression that was in fact introduced a few lines above at [`R289`](https://github.com/flozender/jgit/commit/298486a7c320629de12f9506e0133686a7382b01#diff-412275d04b0bd690cda01a7775aa1eb076e7d1cd385d80bdb831f885891d9c5dR289), which might be causing the problem

**Comment by tsantalis** [comment]
![Screenshot from 2022-12-12 15-03-20](https://user-images.githubusercontent.com/1483516/207143597-76b40618-07e2-41a9-90cf-3611e8efdf8e.png)
