### ISSUE TITLE
Invalid Change History - Split conditional with extract variable

### ISSUE THREAD

**Issue by flozender** [jodavimehran/code-tracker#88]
https://github.com/flozender/jgit/commit/1080cc5a0d67012c0ef08d9468fbbc9d90b0c238#diff-412275d04b0bd690cda01a7775aa1eb076e7d1cd385d80bdb831f885891d9c5dR402

The `if block` here is shown as `introduced` but should be `block split` considering the extracted variable.

**Comment by tsantalis** [comment]
Split Conditional if(dirCacheEntry != null && dirCacheEntry.getStage() > 0) to [if(dirCacheEntry != null), if(stage > 0)] in method public diff(monitor ProgressMonitor, estWorkTreeSize int, estIndexSize int, title String) : boolean from class org.eclipse.jgit.lib.IndexDiff

Extract Variable stage : int in method public diff(monitor ProgressMonitor, estWorkTreeSize int, estIndexSize int, title String) : boolean from class org.eclipse.jgit.lib.IndexDiff

Extract Variable path : String in method public diff(monitor ProgressMonitor, estWorkTreeSize int, estIndexSize int, title String) : boolean from class org.eclipse.jgit.lib.IndexDiff
